<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="576" started-at="2020-01-05T21:15:13 CST" finished-at="2020-01-05T21:15:14 CST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="576" started-at="2020-01-05T21:15:13 CST" finished-at="2020-01-05T21:15:14 CST">
      <class name="io.restassured.test.GetTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:io.restassured.test.GetTest@5ae63ade]" name="setUp" is-config="true" duration-ms="508" started-at="2020-01-05T21:15:13 CST" finished-at="2020-01-05T21:15:14 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getList()[pri:1, instance:io.restassured.test.GetTest@5ae63ade]" name="getList" duration-ms="6" started-at="2020-01-05T21:15:14 CST" description="Get the List of user" finished-at="2020-01-05T21:15:14 CST">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
The method given() is undefined for the type GetTest
The method equalTo(int) is undefined for the type GetTest
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
The method given() is undefined for the type GetTest
The method equalTo(int) is undefined for the type GetTest

at io.restassured.test.GetTest.getList(GetTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getList -->
      </class> <!-- io.restassured.test.GetTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
